-- liquibase formatted sql

-- changeSet Danil:2
create table car
(
    id           int generated by default as identity primary key,
    model_name   varchar,
    horse_powers int,
    description  varchar,
    category     varchar,
    price        int
);
-- rollback drop table car;