-- liquibase formatted sql

-- changeSet Danil:1
create table person
(
    id            int generated by default as identity primary key,
    email         varchar(100) unique,
    password      varchar(100),
    name          varchar(150),
    tel           varchar(16),
    date_of_birth date,
    role          varchar
);
-- rollback drop table person;